### ISSUE TITLE
【前端】作品下单与活动众筹的前端支付接口

### ISSUE THREAD

**Issue by KumaLoveliver** [StarSeaProject/starrysea2#88]
1、作品下单时的快递费将使用线上支付，目前后台的接口已经写好，前端这边需要在调用下单接口时，把支付金额传到后台。
支付金额是根据收货地址进行计算的，不需要体现在页面上，但具体的还需要等木木提供每个地区的快递费表，然后后台写一个接口给前端获取。

2、用户参与众筹也是统一通过线上支付完成，目前后台的接口还需要改动，但前端这边还需要写一个可以让用户输入金额的页面，例如用户输入100则表示将支付100RMB到该活动中。
UI设计交由J总设计。

**Comment by jzeri** [comment]
[众筹金额.zip](https://github.com/StarSeaProject/starrysea2/files/3101188/default.zip)

**Comment by jzeri** [comment]
和木木商量了决定把金额放在众筹页面中，输入金额数目，点击确定跳到第四方的支付页面进行支付

**Comment by KumaLoveliver** [comment]
作品下单的支付金额不需要前端传，后台会根据收货地址自动计算。
但是最好把支付的金额在填写下单信息时就显示出来，具体接口等待木木传快递费的xls

**Comment by KumaLoveliver** [comment]
接口已经完成，下单的接口不变，众筹接口为/activity/funding/participate，具体可看swagger

**Comment by KumaLoveliver** [comment]
还有下单的时候的邮费回显，接口已经完成，接口为/order/postage/money，具体可看swagger。
要注意如果某个省份没有邮费记录的话会返回0的情况
