### ISSUE TITLE
【业务】快递费xls表提供

### ISSUE THREAD

**Issue by KumaLoveliver** [StarSeaProject/starrysea2#90]
需要提供一份顺丰的青岛到全国各地的快递费xls表。
表中的信息包括【目的地】、【金额】，如果一个收货地有多种快递服务可以选择则选择最便宜的。

**Comment by mumuzhizhi** [comment]
[快递.xlsx](https://github.com/StarSeaProject/starrysea2/files/3103437/default.xlsx)
如上所示

**Comment by KumaLoveliver** [comment]
还需要对xls表进行再加工以方便录入数据库

**Comment by mumuzhizhi** [comment]
[省份邮费改.xlsx](https://github.com/StarSeaProject/starrysea2/files/3103757/default.xlsx)

**Comment by KumaLoveliver** [comment]
修改邮费xls，青海省统一收取23块
[default.zip](https://github.com/StarSeaProject/starrysea2/files/3103881/default.zip)
